### ISSUE TITLE
Forced to use keystore file?

### ISSUE THREAD

**Issue by jay5656** [FFDA/revanced-cli-gui#2]
Im a little confused, i may not be doing this right but im trying to patch tiktok, and i have the option to use a keystore file off but i keep getting this error. What am i doing wrong?

INFO: Aligning APK 
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
	at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:52)
	at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:113)
	at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:165)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:336)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
	... 15 more

**Comment by FFDA** [comment]
I only created the front-end for Revanced-CLI, while the back-end is developed by the Revanced team. I am not affiliated with them in any way. Moreover, this program only creates Revanced-CLI commands from your selected options and passes them to it for patching, etc.

That out of the way.

The option to use the same keystore store file is useful to make updating the same app easier. If you sign the app with a different keystore file, you won’t be able to update the app on your phone. Instead, you’ll have to uninstall the previous version before installing the new one; otherwise, the installation will fail.
If you do not check this option Revanced-CLI will simply extract/create a keystore from the apk you try to patch and use it. And will do it for every new app, so every apk will be singed with new keystore file and you won't be able to update them without uninstalling the previous version.

I can try to help you debug, but I only used this program to patch YouTube every thew weeks, so my knowledge will be limited. That said, I just downloaded the latest version of TikTok from APKPure and was able to patch it with the `Use keystore file` option both enabled and disabled without any issues.

Quick google search gave me [this result](https://www.reddit.com/r/revancedapp/comments/w9o5vv/getting_a_keystoreexception_while_creating_a/). Could this be a reason? Is this the first time you are using Revanced-CLI-GUI?

It would be useful if you could provide the command used for patching. Just tick the `Print patch command` checkbox on and try to patch it again. And you will see out put that looks like this `Patching command: java -jar ...`. Maybe that will give me a clue.

**Comment by jay5656** [comment]
Im okay with every app being signed with new keystore file and not being able to update them without uninstalling. 

its not my first time, originally i tried to learn how to do it without a GUI but it was really hard to understand the commands. So i used rvx-builder which is a GUI to do it, but unfortunately right now it doesnt seem to work

I completely forgot I uninstalled the zulu 17 JDK im so sorry, but thank you for helping it works now!
